/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Feb 26 15:30:28 GMT 2020
 */

package com.puppycrawl.tools.checkstyle.checks.indentation;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class AbstractExpressionHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\ronys\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\ronys\\git\\checkstyle"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\ronys"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "ronys"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader() ,
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel",
      "com.puppycrawl.tools.checkstyle.api.Context",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LambdaHandler",
      "antlr.collections.AST",
      "com.puppycrawl.tools.checkstyle.api.FileContents",
      "com.puppycrawl.tools.checkstyle.checks.indentation.WhileHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LabelHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.DoWhileHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.CatchHandler",
      "org.apache.commons.beanutils.ConvertUtilsBean",
      "com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter",
      "com.puppycrawl.tools.checkstyle.checks.indentation.CaseHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineWrappingHandler$LineWrappingOptions",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MethodCallHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ElseHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ForHandler",
      "com.puppycrawl.tools.checkstyle.api.AbstractCheck",
      "com.puppycrawl.tools.checkstyle.checks.indentation.SwitchHandler",
      "com.puppycrawl.tools.checkstyle.utils.CommonUtil",
      "com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory",
      "org.apache.commons.beanutils.Converter",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MemberDefHandler",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean",
      "com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IfHandler",
      "com.puppycrawl.tools.checkstyle.api.DetailAST",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineSet",
      "com.puppycrawl.tools.checkstyle.api.CheckstyleException",
      "com.puppycrawl.tools.checkstyle.api.SeverityLevel",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ObjectBlockHandler",
      "org.apache.commons.beanutils.ConversionException",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ArrayInitHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ImportHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck",
      "com.puppycrawl.tools.checkstyle.checks.indentation.SlistHandler",
      "com.puppycrawl.tools.checkstyle.api.LocalizedMessage",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MethodDefHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.TryHandler",
      "com.puppycrawl.tools.checkstyle.FileStatefulCheck",
      "com.puppycrawl.tools.checkstyle.checks.indentation.PrimordialHandler",
      "com.puppycrawl.tools.checkstyle.api.Contextualizable",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineWrappingHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ClassDefHandler",
      "com.puppycrawl.tools.checkstyle.api.Configurable",
      "com.puppycrawl.tools.checkstyle.checks.indentation.PackageDefHandler",
      "org.apache.commons.beanutils.BeanUtilsBean",
      "com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.NewHandler",
      "com.puppycrawl.tools.checkstyle.grammar.CommentListener",
      "com.puppycrawl.tools.checkstyle.api.Configuration",
      "com.puppycrawl.tools.checkstyle.api.AbstractCheck$FileContext",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndexHandler"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.puppycrawl.tools.checkstyle.api.DetailAST", false, AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory", false, AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck", false, AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.puppycrawl.tools.checkstyle.checks.indentation.LineSet", false, AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("com.puppycrawl.tools.checkstyle.checks.indentation.LineWrappingHandler", false, AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(AbstractExpressionHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.puppycrawl.tools.checkstyle.checks.indentation.AbstractExpressionHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineWrappingHandler$LineWrappingOptions",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean",
      "com.puppycrawl.tools.checkstyle.api.AbstractViolationReporter",
      "com.puppycrawl.tools.checkstyle.api.AbstractCheck",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndentationCheck",
      "com.puppycrawl.tools.checkstyle.checks.indentation.PrimordialHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndentLevel",
      "com.puppycrawl.tools.checkstyle.checks.indentation.BlockParentHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IfHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ForHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.SlistHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ArrayInitHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ClassDefHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ObjectBlockHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.PackageDefHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LabelHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LambdaHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ImportHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.SwitchHandler",
      "com.puppycrawl.tools.checkstyle.utils.CommonUtil",
      "com.puppycrawl.tools.checkstyle.checks.indentation.TryHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.IndexHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.StaticInitHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.SynchronizedHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.CaseHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MethodCallHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.CatchHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.WhileHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MethodDefHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.MemberDefHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.NewHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.ElseHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineSet",
      "com.puppycrawl.tools.checkstyle.checks.indentation.DoWhileHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.FinallyHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.LineWrappingHandler",
      "com.puppycrawl.tools.checkstyle.checks.indentation.HandlerFactory",
      "com.puppycrawl.tools.checkstyle.api.TokenTypes",
      "com.puppycrawl.tools.checkstyle.utils.TokenUtil"
    );
  }
}
