/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Feb 26 15:43:45 GMT 2020
 */

package com.puppycrawl.tools.checkstyle.ant;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class CheckstyleAntTask_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\ronys\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\ronys\\git\\checkstyle"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\ronys"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "ronys"); 
    java.lang.System.setProperty("user.timezone", ""); 
    java.lang.System.setProperty("sun.boot.class.path", "C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\resources.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\rt.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\sunrsasign.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\jsse.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\jce.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\charsets.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\lib\\jfr.jar;C:\\Program Files\\Java\\jdk1.8.0_231\\jre\\classes"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(CheckstyleAntTask_ESTest_scaffolding.class.getClassLoader() ,
      "com.puppycrawl.tools.checkstyle.AuditEventFormatter",
      "com.puppycrawl.tools.checkstyle.api.Context",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Property",
      "org.apache.commons.beanutils.ConversionException",
      "com.puppycrawl.tools.checkstyle.api.Contextualizable",
      "com.puppycrawl.tools.checkstyle.PropertyResolver",
      "com.puppycrawl.tools.checkstyle.ModuleFactory",
      "com.puppycrawl.tools.checkstyle.api.AuditListener",
      "com.puppycrawl.tools.checkstyle.api.Configurable",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean$OutputStreamOptions",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Formatter",
      "org.apache.commons.beanutils.Converter",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean",
      "com.puppycrawl.tools.checkstyle.api.Configuration",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Listener",
      "com.puppycrawl.tools.checkstyle.DefaultLogger",
      "com.puppycrawl.tools.checkstyle.api.SeverityLevelCounter",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask",
      "com.puppycrawl.tools.checkstyle.AuditEventDefaultFormatter",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$FormatterType",
      "com.puppycrawl.tools.checkstyle.api.RootModule",
      "com.puppycrawl.tools.checkstyle.XMLLogger",
      "com.puppycrawl.tools.checkstyle.api.AuditEvent",
      "com.puppycrawl.tools.checkstyle.api.CheckstyleException"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.io.File", false, CheckstyleAntTask_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.tools.ant.types.FileSet", false, CheckstyleAntTask_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.tools.ant.types.Reference", false, CheckstyleAntTask_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(CheckstyleAntTask_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Property",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Formatter",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$FormatterType",
      "com.puppycrawl.tools.checkstyle.api.SeverityLevel",
      "com.puppycrawl.tools.checkstyle.ThreadModeSettings",
      "com.puppycrawl.tools.checkstyle.ConfigurationLoader$IgnoredModulesOptions",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean$OutputStreamOptions",
      "com.puppycrawl.tools.checkstyle.api.AutomaticBean",
      "com.puppycrawl.tools.checkstyle.DefaultLogger",
      "com.puppycrawl.tools.checkstyle.AuditEventDefaultFormatter",
      "com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask$Listener",
      "com.puppycrawl.tools.checkstyle.XMLLogger"
    );
  }
}
