/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 15:47:57 GMT 2020
 */

package com.puppycrawl.tools.checkstyle.gui;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.DetailAstImpl;
import com.puppycrawl.tools.checkstyle.api.DetailAST;
import com.puppycrawl.tools.checkstyle.gui.MainFrameModel;
import com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseTreeTablePresentation_ESTest extends ParseTreeTablePresentation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      DetailAstImpl detailAstImpl1 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(detailAstImpl1);
      parseTreeTablePresentation0.getChildCount(detailAstImpl0);
      ParseTreeTablePresentation parseTreeTablePresentation1 = new ParseTreeTablePresentation(detailAstImpl1);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChildCount(detailAstImpl0);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      DetailAstImpl detailAstImpl1 = (DetailAstImpl)parseTreeTablePresentation0.getChild(detailAstImpl0, 0);
      parseTreeTablePresentation0.isLeaf(detailAstImpl1);
      parseTreeTablePresentation0.getValueAt((Object) null, 0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      int int0 = 3;
      parseTreeTablePresentation0.getColumnClass(3);
      parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getRoot();
      int int1 = 4;
      parseTreeTablePresentation0.getRoot();
      Object object0 = null;
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      Integer integer0 = (Integer)parseTreeTablePresentation0.getValueAt(detailAstImpl0, 2);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild(integer0, 3);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getColumnClass(3);
      parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getRoot();
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isCellEditable(16);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      parseTreeTablePresentation0.getIndexOfChild(detailAstImpl0, (Object) null);
      parseTreeTablePresentation0.getColumnName(4);
      parseTreeTablePresentation0.getChildCount(detailAstImpl0);
      parseTreeTablePresentation0.isCellEditable(10037);
      parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getColumnClass(3);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount("Tree");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChild(detailAstImpl0, (-2574));
      parseTreeTablePresentation0.getChildCount(object0);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      DetailAstImpl detailAstImpl1 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(detailAstImpl1);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.isLeaf(mainFrameModel_ParseMode0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.gui.MainFrameModel$ParseMode cannot be cast to antlr.collections.AST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      int int0 = 3;
      parseTreeTablePresentation0.getColumnClass(3);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getRoot();
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isCellEditable(16);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      parseTreeTablePresentation0.getIndexOfChild(detailAstImpl0, (Object) null);
      parseTreeTablePresentation0.getColumnName(4);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getIndexOfChild("Text", object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getRoot();
      Object object0 = parseTreeTablePresentation0.getRoot();
      Object object1 = parseTreeTablePresentation0.getValueAt(object0, 3);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount(object1);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Integer cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChildCount(object0);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild(object0, 1683);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.PLAIN_JAVA;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      parseTreeTablePresentation0.getColumnCount();
      MainFrameModel.ParseMode mainFrameModel_ParseMode1 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode1);
      parseTreeTablePresentation0.getRoot();
      // Undeclared exception!
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getColumnName(1);
      parseTreeTablePresentation0.getIndexOfChild(object0, "Type");
      parseTreeTablePresentation0.getColumnClass(0);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getValueAt(object0, 1);
      parseTreeTablePresentation0.getIndexOfChild(object0, "EOF");
      parseTreeTablePresentation0.getColumnClass(4);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChildCount(object0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild(object0, 1683);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getColumnClass(3);
      parseTreeTablePresentation0.getRoot();
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getValueAt(object0, 4);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount("ROOT");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getChildCount(object0);
      Object object1 = parseTreeTablePresentation0.getRoot();
      Object object2 = null;
      parseTreeTablePresentation0.getChild(object1, 0);
      int int0 = 2977;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt((Object) null, 2977);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getIndexOfChild((Object) null, "<missing token>");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getValueAt((Object) null, 0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      int int0 = (-3890);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt("com.puppycrawl.tools.checkstyle.api.JavadocTokenTypes", (-3890));
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getValueAt(object0, 1);
      parseTreeTablePresentation0.getIndexOfChild(object0, "EOF");
      parseTreeTablePresentation0.getColumnClass(0);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(object0);
      parseTreeTablePresentation0.getRoot();
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.isLeaf(mainFrameModel_ParseMode0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.gui.MainFrameModel$ParseMode cannot be cast to antlr.collections.AST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DetailAST detailAST0 = mock(DetailAST.class, new ViolatedAssumptionAnswer());
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      String string0 = "";
      int int0 = 0;
      DetailAST detailAST1 = mock(DetailAST.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.setParseTree(detailAST1);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.api.DetailAST$MockitoMock$952659172 cannot be cast to antlr.collections.AST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = "_|x-Y`Mw.H~";
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.PLAIN_JAVA;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount(mainFrameModel_ParseMode0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.gui.MainFrameModel$ParseMode cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getColumnName(17);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 17
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getIndexOfChild("", "");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getColumnClass(0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.isLeaf((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.isCellEditable(4);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.getColumnCount();
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild(object0, 10071);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt(object0, 882);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      int int0 = 1;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt((Object) null, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getChild(object0, (-4119));
      int int0 = 285;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild((Object) null, 285);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getColumnClass((-1932));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      ParseTreeTablePresentation parseTreeTablePresentation1 = new ParseTreeTablePresentation((DetailAST) null);
      int int0 = (-1266);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation1.getChild(parseTreeTablePresentation0, (-1266));
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getColumnCount();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(object0);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.PLAIN_JAVA;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      int int0 = 10048;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getColumnClass(10048);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.isLeaf(mainFrameModel_ParseMode0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.gui.MainFrameModel$ParseMode cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_COMMENTS;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getColumnClass((-1104));
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DetailAST detailAST0 = mock(DetailAST.class, new ViolatedAssumptionAnswer());
      ParseTreeTablePresentation parseTreeTablePresentation0 = null;
      try {
        parseTreeTablePresentation0 = new ParseTreeTablePresentation(detailAST0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.api.DetailAST$MockitoMock$952659172 cannot be cast to antlr.collections.AST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getIndexOfChild(object0, "");
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt((Object) null, 2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getRoot();
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      DetailAstImpl detailAstImpl1 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(detailAstImpl1);
      parseTreeTablePresentation0.getChildCount(detailAstImpl0);
      parseTreeTablePresentation0.getColumnCount();
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      int int0 = 3;
      parseTreeTablePresentation0.getColumnClass(3);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getRoot();
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      int int1 = 16;
      parseTreeTablePresentation0.isCellEditable(16);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      parseTreeTablePresentation0.getIndexOfChild(detailAstImpl0, detailAstImpl0);
      parseTreeTablePresentation0.getColumnName(4);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getIndexOfChild("Text", object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getValueAt(object0, 4);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChildCount("ROOT");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.getValueAt(object0, 1);
      parseTreeTablePresentation0.getIndexOfChild(object0, "EOF");
      parseTreeTablePresentation0.getColumnClass(0);
      parseTreeTablePresentation0.getColumnCount();
      parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.PLAIN_JAVA;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      parseTreeTablePresentation0.getColumnClass(1);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild("EOF", 5);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to com.puppycrawl.tools.checkstyle.api.DetailAST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChildCount(detailAstImpl0);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      int int0 = 1683;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getChild(detailAstImpl0, 1683);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      MainFrameModel.ParseMode mainFrameModel_ParseMode0 = MainFrameModel.ParseMode.JAVA_WITH_JAVADOC_AND_COMMENTS;
      parseTreeTablePresentation0.setParseMode(mainFrameModel_ParseMode0);
      Object object1 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.setParseTree((DetailAST) null);
      parseTreeTablePresentation0.getChild(object1, (-2551));
      parseTreeTablePresentation0.getChildCount(object0);
      parseTreeTablePresentation0.getValueAt(object0, 0);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.isLeaf((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DetailAST detailAST0 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      Object object0 = parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isLeaf(object0);
      int int0 = 10048;
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getColumnClass(10048);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      DetailAST detailAST0 = mock(DetailAST.class, new ViolatedAssumptionAnswer());
      Object object0 = null;
      Object object1 = null;
      ParseTreeTablePresentation parseTreeTablePresentation0 = null;
      try {
        parseTreeTablePresentation0 = new ParseTreeTablePresentation(detailAST0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // com.puppycrawl.tools.checkstyle.api.DetailAST$MockitoMock$952659172 cannot be cast to antlr.collections.AST
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      ParseTreeTablePresentation parseTreeTablePresentation0 = new ParseTreeTablePresentation((DetailAST) null);
      parseTreeTablePresentation0.getRoot();
      DetailAstImpl detailAstImpl0 = (DetailAstImpl)parseTreeTablePresentation0.getRoot();
      parseTreeTablePresentation0.isCellEditable(16);
      parseTreeTablePresentation0.setParseTree(detailAstImpl0);
      parseTreeTablePresentation0.getIndexOfChild(detailAstImpl0, (Object) null);
      parseTreeTablePresentation0.getColumnName(4);
      // Undeclared exception!
      try { 
        parseTreeTablePresentation0.getValueAt((Object) null, 16);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Unknown column
         //
         verifyException("com.puppycrawl.tools.checkstyle.gui.ParseTreeTablePresentation", e);
      }
  }
}
