/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 15:24:58 GMT 2020
 */

package com.puppycrawl.tools.checkstyle.checks.modifier;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.puppycrawl.tools.checkstyle.DetailAstImpl;
import com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RedundantModifierCheck_ESTest extends RedundantModifierCheck_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      detailAstImpl0.initialize(3355, "redundantModifier");
      redundantModifierCheck0.visitToken(detailAstImpl0);
      assertFalse(redundantModifierCheck0.isCommentNodesRequired());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      int[] intArray0 = redundantModifierCheck0.getAcceptableTokens();
      assertArrayEquals(new int[] {9, 10, 161, 15, 8, 14, 154, 178}, intArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      redundantModifierCheck0.visitToken(detailAstImpl0);
      assertEquals(0, detailAstImpl0.getLine());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      detailAstImpl0.setType(9);
      // Undeclared exception!
      try { 
        redundantModifierCheck0.visitToken(detailAstImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      detailAstImpl0.initialize(8, "redundantModifier");
      // Undeclared exception!
      try { 
        redundantModifierCheck0.visitToken(detailAstImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      detailAstImpl0.initialize(15, "redundantModifier");
      // Undeclared exception!
      try { 
        redundantModifierCheck0.visitToken(detailAstImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      int[] intArray0 = redundantModifierCheck0.getRequiredTokens();
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      DetailAstImpl detailAstImpl0 = new DetailAstImpl();
      detailAstImpl0.initialize(178, "redundantModifier");
      // Undeclared exception!
      try { 
        redundantModifierCheck0.visitToken(detailAstImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.puppycrawl.tools.checkstyle.checks.modifier.RedundantModifierCheck", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      RedundantModifierCheck redundantModifierCheck0 = new RedundantModifierCheck();
      int[] intArray0 = redundantModifierCheck0.getDefaultTokens();
      assertArrayEquals(new int[] {9, 10, 161, 15, 8, 14, 154, 178}, intArray0);
  }
}
